"""Add client_code and brand fields

Revision ID: 019474a8fafc
Revises: 
Create Date: 2025-11-21 14:01:14.119160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019474a8fafc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add columns as nullable first
    op.add_column('clients', sa.Column('client_code', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('misc_info', sa.String(), nullable=True))
    op.add_column('master', sa.Column('brand', sa.String(), nullable=True))

    # 2. Data Migration
    # Copy project -> brand in master
    op.execute("UPDATE master SET brand = project")
    
    # Backfill clients: Re-populate from master to ensure consistency
    # We delete existing clients because the definition of a "client" row has changed 
    # from just "Name" to "Name + Misc Info + Code"
    op.execute("DELETE FROM clients")
    op.execute("""
        INSERT INTO clients (client_name, client_code, misc_info, created_at, created_by)
        SELECT DISTINCT client_name, client_code, misc_info, created_at, created_by
        FROM master
    """)

    # 3. Apply constraints and cleanup
    op.alter_column('clients', 'client_code', nullable=False)
    op.alter_column('clients', 'misc_info', nullable=False)
    
    op.drop_constraint('clients_client_name_key', 'clients', type_='unique')
    op.create_unique_constraint(None, 'clients', ['client_code'])
    
    op.drop_constraint('master_client_code_key', 'master', type_='unique')
    op.drop_column('master', 'project')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('master_client_code_key'), 'master', ['client_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('master', 'brand')
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_unique_constraint(op.f('clients_client_name_key'), 'clients', ['client_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('clients', 'misc_info')
    op.drop_column('clients', 'client_code')
    # ### end Alembic commands ###
