"""Add creation_mode to Master

Revision ID: dbe7367ac1a4
Revises: 33a614ca3359
Create Date: 2025-11-24 15:37:07.429903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe7367ac1a4'
down_revision: Union[str, Sequence[str], None] = '33a614ca3359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('creation_mode', sa.String(), nullable=True))
    op.alter_column('master', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('master', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('master', 'creation_mode')
    # ### end Alembic commands ###
